<a href="https://colab.research.google.com/github/thaiyenphung/thaiyenphung-DataScience-2025/blob/main/Completed/06-Working_with_Data/05-basic_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🧼 Cleaning Dirty Data (Missing Values & Type Fixes)

## 🔹 LEARNING GOALS:
- Detect and count missing values (`NaN`)
- Fill or drop missing data
- Convert column data types safely
- Understand the difference between `NaN`, `None`, `""`, and type mismatches

### 🧪 1. Load a Messy Dataset

In [ ]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", None],
    "Age": ["25", "thirty", 35, np.nan, "40"],
    "Signup Date": ["2022-01-01", "not a date", "2022/03/01", None, "April 5, 2022"],
    "Score": [95.5, None, 88.0, 92.5, ""]
}

df = pd.DataFrame(data)
df

      Name     Age    Signup Date Score
0    Alice      25     2022-01-01  95.5
1      Bob  thirty     not a date  None
2  Charlie      35     2022/03/01  88.0
3    David     NaN           None  92.5
4     None      40  April 5, 2022

### 🧯 2. Detecting Missing or Broken Values

In [ ]:
df.isnull()

    Name    Age  Signup Date  Score
0  False  False        False  False
1  False  False        False   True
2  False  False        False  False
3  False   True         True  False
4   True  False        False  False

In [ ]:
df.isnull().sum()

Name           1
Age            1
Signup Date    1
Score          1
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)]

    Name     Age    Signup Date Score
1    Bob  thirty     not a date  None
3  David     NaN           None  92.5
4   None      40  April 5, 2022

### 🧹 3. Cleaning Strategy Options

In [ ]:
df.fillna({
    "Name": "Unknown",
    "Age": -1,
    "Signup Date": "1970-01-01",
    "Score": 0.0
})

      Name     Age    Signup Date Score
0    Alice      25     2022-01-01  95.5
1      Bob  thirty     not a date   0.0
2  Charlie      35     2022/03/01  88.0
3    David      -1     1970-01-01  92.5
4  Unknown      40  April 5, 2022

In [ ]:
df.dropna()

      Name Age Signup Date Score
0    Alice  25  2022-01-01  95.5
2  Charlie  35  2022/03/01  88.0

### 🧬 4. Data Type Fixes

In [ ]:
df.dtypes

Name           object
Age            object
Signup Date    object
Score          object
dtype: object

In [ ]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Score"] = pd.to_numeric(df["Score"], errors="coerce")
df["Signup Date"] = pd.to_datetime(df["Signup Date"], errors="coerce")
df.dtypes

Name                   object
Age                   float64
Signup Date    datetime64[ns]
Score                 float64
dtype: object

### 🩹 5. Impute (Fill In) Fixed Missing Values

In [ ]:
df["Age"].fillna(df["Age"].median(), inplace=True)
df["Score"].fillna(df["Score"].mean(), inplace=True)

/tmp/ipython-input-1713118361.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].median(), inplace=True)
/tmp/ipython-input-1713118361.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Score"].fillna(df["Score"].mean(), inplace=True)

In [ ]:
df["Signup Date"].fillna(df["Signup Date"].min(), inplace=True)

/tmp/ipython-input-3000949103.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Signup Date"].fillna(df["Signup Date"].min(), inplace=True)

In [ ]:
df["Name"].fillna("Unknown", inplace=True)

/tmp/ipython-input-626038248.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Name"].fillna("Unknown", inplace=True)

### 🤓 6. Cleaned Data Review

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         5 non-null      object
 1   Age          5 non-null      float64
 2   Signup Date  5 non-null      datetime64[ns]
 3   Score        5 non-null      float64
dtypes: datetime64[ns](1), float64(2), object(1)
memory usage: 292.0+ bytes

In [ ]:
df.describe(include="all")

         Name        Age          Signup Date     Score
count       5   5.000000                    5   5.00000
unique      5        NaN                  NaN       NaN
top     Alice        NaN                  NaN       NaN
freq        1        NaN                  NaN       NaN
mean      NaN  34.000000  2022-01-01 00:00:00  92.00000
min       NaN  25.000000  2022-01-01 00:00:00  88.00000
25%       NaN  35.000000  2022-01-01 00:00:00  92.00000
50%       NaN  35.000000  2022-01-01 00:00:00  92.00000
75%       NaN  35.000000  2022-01-01 00:00:00  92.50000
max       NaN  40.000000  2022-01-01 00:00:00  95.50000
std       NaN   5.477226                  NaN   2.66927

### 🧪 Try It Yourself

Modify the `data` dictionary at the top of this notebook. Add:
- A new column with some `None` and `""` values
- At least one row with all columns filled incorrectly
Then re-run the notebook and fix it step-by-step.

In [ ]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", None, None],
    "Age": ["25", "thirty", 35, np.nan, "40", "twenty-nine"],
    "Signup Date": ["2022-01-01", "not a date", "2022/03/01", None, "April 5, 2022", "this morning"],
    "Score": [95.5, None, 88.0, 92.5, "", ""],
    "Email": ["alice@yahoo.com", None, "bob@gmail.com", "", "phung@gmail.com", None]
}

df = pd.DataFrame(data)
df

      Name          Age    Signup Date Score            Email
0    Alice           25     2022-01-01  95.5  alice@yahoo.com
1      Bob       thirty     not a date  None             None
2  Charlie           35     2022/03/01  88.0    bob@gmail.com
3    David          NaN           None  92.5
4     None           40  April 5, 2022        phung@gmail.com
5     None  twenty-nine   this morning                   None

In [ ]:
# Detecting missing or broken values
df.isnull()

    Name    Age  Signup Date  Score  Email
0  False  False        False  False  False
1  False  False        False   True   True
2  False  False        False  False  False
3  False   True         True  False  False
4   True  False        False  False  False
5   True  False        False  False   True

In [ ]:
# Counting nulls before cleaning
df.isnull().sum()

Name           2
Age            1
Signup Date    1
Score          1
Email          2
dtype: int64

In [ ]:
# Rows that have missing or broken values
df[df.isnull().any(axis=1)]

    Name          Age    Signup Date Score            Email
1    Bob       thirty     not a date  None             None
3  David          NaN           None  92.5
4   None           40  April 5, 2022        phung@gmail.com
5   None  twenty-nine   this morning                   None

In [ ]:
# Convert "" to np.nan
df = df.replace("", np.nan)

/tmp/ipython-input-3585831073.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace("", np.nan)

In [ ]:
# Check types before conversion
df.dtypes

Name            object
Age             object
Signup Date     object
Score          float64
Email           object
dtype: object

In [ ]:
# Convert to proper types
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Score"] = pd.to_numeric(df["Score"], errors="coerce")
df["Signup Date"] = pd.to_datetime(df["Signup Date"], errors="coerce")

# Show data types after conversion
df.dtypes

Name                   object
Age                   float64
Signup Date    datetime64[ns]
Score                 float64
Email                  object
dtype: object

In [ ]:
# Fill in missing values
median_age = df["Age"].median()
mean_score = df["Score"].mean()
date = df["Signup Date"].min()

# Print fill values
print("Age:", median_age)
print("Score:", mean_score)
print("Signup Date:", date)

Age: 35.0
Score: 92.0
Signup Date: 2022-01-01 00:00:00

In [ ]:
# Impute missing values
df = df.fillna({
    "Name": "Unknown",
    "Age": median_age,
    "Score": mean_score,
    "Signup Date": date,
    "Email": "example@gmail.com"
})

# Verify the result
print(df.isnull().sum())

Name           0
Age            0
Signup Date    0
Score          0
Email          0
dtype: int64

In [ ]:
# Print DataFrame with fixed values
print(df)

      Name   Age Signup Date  Score              Email
0    Alice  25.0  2022-01-01   95.5    alice@yahoo.com
1      Bob  35.0  2022-01-01   92.0  example@gmail.com
2  Charlie  35.0  2022-01-01   88.0      bob@gmail.com
3    David  35.0  2022-01-01   92.5  example@gmail.com
4  Unknown  40.0  2022-01-01   92.0    phung@gmail.com
5  Unknown  35.0  2022-01-01   92.0  example@gmail.com

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         6 non-null      object
 1   Age          6 non-null      float64
 2   Signup Date  6 non-null      datetime64[ns]
 3   Score        6 non-null      float64
 4   Email        6 non-null      object
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 372.0+ bytes

In [ ]:
df.describe(include="all")

           Name        Age          Signup Date      Score              Email
count         6   6.000000                    6   6.000000                  6
unique        5        NaN                  NaN        NaN                  4
top     Unknown        NaN                  NaN        NaN  example@gmail.com
freq          2        NaN                  NaN        NaN                  3
mean        NaN  34.166667  2022-01-01 00:00:00  92.000000                NaN
min         NaN  25.000000  2022-01-01 00:00:00  88.000000                NaN
25%         NaN  35.000000  2022-01-01 00:00:00  92.000000                NaN
50%         NaN  35.000000  2022-01-01 00:00:00  92.000000                NaN
75%         NaN  35.000000  2022-01-01 00:00:00  92.375000                NaN
max         NaN  40.000000  2022-01-01 00:00:00  95.500000                NaN
std         NaN   4.915960                  NaN   2.387467                NaN

### 🧠 Mini-Challenge

> 🗂 Load `"data/survey.csv"` and:
- Identify which columns have missing values
- Use `.isnull().sum()` to get a null report
- Use a mix of `.fillna()`, `.dropna()`, and `pd.to_numeric()` or `pd.to_datetime()` to clean it
- Print a summary with `.info()` and `.describe()`

# "survey.csv" file couldn't be found
# I uploaded pokemon.csv to use for this assignment

In [ ]:
# Load the "pokemon.csv" file
from google.colab import files
uploaded = files.upload()

Saving pokemon.csv to pokemon (1).csv

In [ ]:
import pandas as pd
df1 = pd.read_csv("pokemon.csv")
df1.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [ ]:
# Check for missing values
df1.isnull().sum()

#               0
Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [ ]:
# Fill missing values in Types 2 with "None"
df1['Type 2'] = df1['Type 2'].fillna('None')

df1.isnull().sum()

#             0
Name          0
Type 1        0
Type 2        0
Total         0
HP            0
Attack        0
Defense       0
Sp. Atk       0
Sp. Def       0
Speed         0
Generation    0
Legendary     0
dtype: int64

In [ ]:
# Final summaries
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      800 non-null    object
 4   Total       800 non-null    int64
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB

In [ ]:
df1.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

### 📝 Summary

| Concept        | Tool/Function                      |
|----------------|------------------------------------|
| Detect nulls   | `df.isnull()`, `df.isnull().sum()` |
| Drop rows      | `df.dropna()`                      |
| Fill values    | `df.fillna()`                      |
| Convert types  | `pd.to_numeric()`, `pd.to_datetime()` |
| Replace values | `df.replace()`                     |