<a href="https://colab.research.google.com/github/thaiyenphung/thaiyenphung-DataScience-2025/blob/main/Completed/06-Working_with_Data/06-column_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🧱 Column Operations: Creating, Renaming, and Dropping Columns

## 🔹 LEARNING GOALS:
- Create new columns using calculations or functions
- Rename one or multiple columns
- Drop unwanted columns safely
- Apply functions across columns using `.apply()` and lambdas

### 🏗️ 1. Setup and Sample Data

In [3]:
import pandas as pd

data = {
    "first_name": ["Alice", "Bob", "Charlie", "David"],
    "last_name": ["Smith", "Jones", "Brown", "Wilson"],
    "math_score": [85, 90, 78, 92],
    "science_score": [88, 85, 82, 95]
}

df = pd.DataFrame(data)
df

  first_name last_name  math_score  science_score
0      Alice     Smith          85             88
1        Bob     Jones          90             85
2    Charlie     Brown          78             82
3      David    Wilson          92             95

### ➕ 2. Creating New Columns

In [2]:
# Simple column arithmetic
df["average_score"] = (df["math_score"] + df["science_score"]) / 2
df

  first_name last_name  math_score  science_score  average_score
0      Alice     Smith          85             88           86.5
1        Bob     Jones          90             85           87.5
2    Charlie     Brown          78             82           80.0
3      David    Wilson          92             95           93.5

In [3]:
# Create full name column
df["full_name"] = df["first_name"] + " " + df["last_name"]
df

,first_name,last_name,math_score,science_score,average_score,full_name
0,Alice,Smith,85,88,86.5,Alice Smith
1,Bob,Jones,90,85,87.5,Bob Jones
2,Charlie,Brown,78,82,80.0,Charlie Brown
3,David,Wilson,92,95,93.5,David Wilson

### ✍️ 3. Renaming Columns

In [4]:
# Rename a single column
df.rename(columns={"math_score": "Math", "science_score": "Science"}, inplace=True)
df

  first_name last_name  Math  Science  average_score      full_name
0      Alice     Smith    85       88           86.5    Alice Smith
1        Bob     Jones    90       85           87.5      Bob Jones
2    Charlie     Brown    78       82           80.0  Charlie Brown
3      David    Wilson    92       95           93.5   David Wilson

In [5]:
# Rename all columns to uppercase
df.columns = [col.upper() for col in df.columns]
df

  FIRST_NAME LAST_NAME  MATH  SCIENCE  AVERAGE_SCORE      FULL_NAME
0      Alice     Smith    85       88           86.5    Alice Smith
1        Bob     Jones    90       85           87.5      Bob Jones
2    Charlie     Brown    78       82           80.0  Charlie Brown
3      David    Wilson    92       95           93.5   David Wilson

### ❌ 4. Dropping Columns

In [6]:
# Drop by name
df.drop(columns=["FULL_NAME"], inplace=True)
df

  FIRST_NAME LAST_NAME  MATH  SCIENCE  AVERAGE_SCORE
0      Alice     Smith    85       88           86.5
1        Bob     Jones    90       85           87.5
2    Charlie     Brown    78       82           80.0
3      David    Wilson    92       95           93.5

### 🔁 5. Applying Functions Across Columns

In [7]:
# Categorize based on average score
def grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    else:
        return "C"

df["GRADE"] = df["AVERAGE_SCORE"].apply(grade)
df

  FIRST_NAME LAST_NAME  MATH  SCIENCE  AVERAGE_SCORE GRADE
0      Alice     Smith    85       88           86.5     B
1        Bob     Jones    90       85           87.5     B
2    Charlie     Brown    78       82           80.0     B
3      David    Wilson    92       95           93.5     A

### 🧪 Try It Yourself

- Add a new column called `"NAME_LENGTH"` that contains the length of each `FIRST_NAME`
- Create a column `"MATH_PLUS_5"` which is the math score + 5 points bonus

In [11]:
# Add NAME_LENGTH column that contain of length of each FIRST_NAME
df["NAME_LENGTH"] = df["FIRST_NAME"].str.len()

# Add MATH_PLUS_5 column which adds 5 points to the current math score
df["MATH_PLUS_5"] = df["MATH"] + 5

# Print the updated DF
print(df)

  FIRST_NAME LAST_NAME  MATH  SCIENCE  AVERAGE_SCORE GRADE  NAME_LENGTH  \
0      Alice     Smith    85       88           86.5     B            5
1        Bob     Jones    90       85           87.5     B            3
2    Charlie     Brown    78       82           80.0     B            7
3      David    Wilson    92       95           93.5     A            5

   MATH_PLUS_5
0           90
1           95
2           83
3           97

### 🧠 Mini-Challenge

> Load `"data/students.csv"` and:
- Create a `"total_score"` column by summing up all numeric test columns
- Rename any columns that contain spaces (e.g., `"Test 1"`) to use underscores
- Drop any column that contains only `NaN` values

In [1]:
# "students.csv" file couldn't be found
# To complete this mini-challenge, I generated a mock student dataset using
# Mockaroo and saved it as "mock_students.csv"

from google.colab import files
uploaded = files.upload()

Saving mock_students.csv to mock_students.csv

In [4]:
df1 = pd.read_csv("mock_students.csv")
df1.head()

  first_name last_name       full name     id  math_score  english_score
0    Joellen     Askam   Joellen Askam  57818          83             78
1       Toby   Frankis    Toby Frankis  44094          80             97
2      Efrem     Roake     Efrem Roake  46782          91             86
3    Deloris    Maffeo  Deloris Maffeo   6077          99             91
4       Eddy  Fontaine   Eddy Fontaine  54507          67             77

In [5]:
# Create a "total_score" column by summing up all numeric test columns
df1["total_score"] = df1["math_score"] + df1["english_score"]
df1

,first_name,last_name,full name,id,math_score,english_score,total_score
0,Joellen,Askam,Joellen Askam,57818,83,78,161
1,Toby,Frankis,Toby Frankis,44094,80,97,177
2,Efrem,Roake,Efrem Roake,46782,91,86,177
3,Deloris,Maffeo,Deloris Maffeo,6077,99,91,190
4,Eddy,Fontaine,Eddy Fontaine,54507,67,77,144
5,Orton,Stubs,Orton Stubs,83155,92,84,176
6,Pace,Heading,Pace Heading,65015,85,91,176
7,Glori,Rivelin,Glori Rivelin,93605,91,83,174
8,Jeremias,Quernel,Jeremias Quernel,16088,77,81,158
9,Grata,Hrishchenko,Grata Hrishchenko,12133,100,93,193

In [7]:
# Rename columns with spaces to use underscores
df1.rename(columns={"full name": "full_name"}, inplace=True)
df1

,first_name,last_name,full_name,id,math_score,english_score,total_score
0,Joellen,Askam,Joellen Askam,57818,83,78,161
1,Toby,Frankis,Toby Frankis,44094,80,97,177
2,Efrem,Roake,Efrem Roake,46782,91,86,177
3,Deloris,Maffeo,Deloris Maffeo,6077,99,91,190
4,Eddy,Fontaine,Eddy Fontaine,54507,67,77,144
5,Orton,Stubs,Orton Stubs,83155,92,84,176
6,Pace,Heading,Pace Heading,65015,85,91,176
7,Glori,Rivelin,Glori Rivelin,93605,91,83,174
8,Jeremias,Quernel,Jeremias Quernel,16088,77,81,158
9,Grata,Hrishchenko,Grata Hrishchenko,12133,100,93,193

In [8]:
# Check for NaN values
df1.isna().sum()

first_name       0
last_name        0
full_name        0
id               0
math_score       0
english_score    0
total_score      0
dtype: int64

### 📝 Summary

| Action             | Method                                |
|--------------------|----------------------------------------|
| Create column       | `df["new"] = ...`                     |
| Rename column(s)    | `df.rename(columns={...})`            |
| Rename all columns  | `df.columns = [...]`                 |
| Drop column(s)      | `df.drop(columns=[...])`              |
| Apply function      | `df["col"].apply(func)`               |