<a href="https://colab.research.google.com/github/thaiyenphung/thaiyenphung-DataScience-2025/blob/main/Completed/06-Working_with_Data/07-sorting_and_filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🧮 Sorting & Filtering in Pandas

## 🔹 LEARNING GOALS:
- Sort rows using `.sort_values()`
- Filter data using conditional logic
- Chain multiple filters together
- Use `.query()` for readable filtering

# The "students.csv" file coundn't be found.
# I am using the "mock_students.csv" file that I generated using Mockaroo for this notebook.

### 📥 1. Load the Dataset

In [3]:
# Load the "mock_students.csv" file
from google.colab import files
uploaded = files.upload()

Saving mock_students.csv to mock_students.csv

In [4]:
import pandas as pd

df = pd.read_csv("mock_students.csv")
df.head()

  first_name last_name       full name     id  math_score  english_score
0    Joellen     Askam   Joellen Askam  57818          83             78
1       Toby   Frankis    Toby Frankis  44094          80             97
2      Efrem     Roake     Efrem Roake  46782          91             86
3    Deloris    Maffeo  Deloris Maffeo   6077          99             91
4       Eddy  Fontaine   Eddy Fontaine  54507          67             77

### 🔢 2. Sorting Data

In [5]:
# Sort by math_score
df.sort_values(by="math_score")

  first_name    last_name          full name     id  math_score  english_score
4       Eddy     Fontaine      Eddy Fontaine  54507          67             77
8   Jeremias      Quernel   Jeremias Quernel  16088          77             81
1       Toby      Frankis       Toby Frankis  44094          80             97
0    Joellen        Askam      Joellen Askam  57818          83             78
6       Pace      Heading       Pace Heading  65015          85             91
7      Glori      Rivelin      Glori Rivelin  93605          91             83
2      Efrem        Roake        Efrem Roake  46782          91             86
5      Orton        Stubs        Orton Stubs  83155          92             84
3    Deloris       Maffeo     Deloris Maffeo   6077          99             91
9      Grata  Hrishchenko  Grata Hrishchenko  12133         100             93

In [6]:
# Sort by english_score descending
df.sort_values(by="english_score", ascending=False)

  first_name    last_name          full name     id  math_score  english_score
1       Toby      Frankis       Toby Frankis  44094          80             97
9      Grata  Hrishchenko  Grata Hrishchenko  12133         100             93
6       Pace      Heading       Pace Heading  65015          85             91
3    Deloris       Maffeo     Deloris Maffeo   6077          99             91
2      Efrem        Roake        Efrem Roake  46782          91             86
5      Orton        Stubs        Orton Stubs  83155          92             84
7      Glori      Rivelin      Glori Rivelin  93605          91             83
8   Jeremias      Quernel   Jeremias Quernel  16088          77             81
0    Joellen        Askam      Joellen Askam  57818          83             78
4       Eddy     Fontaine      Eddy Fontaine  54507          67             77

In [8]:
# Sort by multiple columns
df.sort_values(by=["english_score", "math_score"], ascending=[False, True])

  first_name    last_name          full name     id  math_score  english_score
1       Toby      Frankis       Toby Frankis  44094          80             97
9      Grata  Hrishchenko  Grata Hrishchenko  12133         100             93
6       Pace      Heading       Pace Heading  65015          85             91
3    Deloris       Maffeo     Deloris Maffeo   6077          99             91
2      Efrem        Roake        Efrem Roake  46782          91             86
5      Orton        Stubs        Orton Stubs  83155          92             84
7      Glori      Rivelin      Glori Rivelin  93605          91             83
8   Jeremias      Quernel   Jeremias Quernel  16088          77             81
0    Joellen        Askam      Joellen Askam  57818          83             78
4       Eddy     Fontaine      Eddy Fontaine  54507          67             77

### 🧪 3. Filtering with Conditions

In [9]:
# Who scored at least 90 in math?
df[df["math_score"] >= 90]

  first_name    last_name          full name     id  math_score  english_score
2      Efrem        Roake        Efrem Roake  46782          91             86
3    Deloris       Maffeo     Deloris Maffeo   6077          99             91
5      Orton        Stubs        Orton Stubs  83155          92             84
7      Glori      Rivelin      Glori Rivelin  93605          91             83
9      Grata  Hrishchenko  Grata Hrishchenko  12133         100             93

In [12]:
# Who scored less than 70 in either subject?
df[(df["math_score"] < 70) | (df["english_score"] < 70)]

  first_name last_name      full name     id  math_score  english_score
4       Eddy  Fontaine  Eddy Fontaine  54507          67             77

### 🔗 4. Combining Filters

In [13]:
# Students with B+ or higher in both
df[(df["math_score"] >= 87) & (df["english_score"] >= 87)]

  first_name    last_name          full name     id  math_score  english_score
3    Deloris       Maffeo     Deloris Maffeo   6077          99             91
9      Grata  Hrishchenko  Grata Hrishchenko  12133         100             93

### 🧾 5. Using `.query()` for Readability

In [14]:
# Same query using .query()
df.query("math_score >= 87 and english_score >= 87")

  first_name    last_name          full name     id  math_score  english_score
3    Deloris       Maffeo     Deloris Maffeo   6077          99             91
9      Grata  Hrishchenko  Grata Hrishchenko  12133         100             93

### 🧪 Try It Yourself

- Sort the dataset by first name alphabetically
- Find students with the same math and science score
- Use `.query()` to find students who scored over 95 in *either* subject

In [16]:
# Sort by first name alphabetically
df.sort_values(by="first_name", ascending=True)

  first_name    last_name          full name     id  math_score  english_score
3    Deloris       Maffeo     Deloris Maffeo   6077          99             91
4       Eddy     Fontaine      Eddy Fontaine  54507          67             77
2      Efrem        Roake        Efrem Roake  46782          91             86
7      Glori      Rivelin      Glori Rivelin  93605          91             83
9      Grata  Hrishchenko  Grata Hrishchenko  12133         100             93
8   Jeremias      Quernel   Jeremias Quernel  16088          77             81
0    Joellen        Askam      Joellen Askam  57818          83             78
5      Orton        Stubs        Orton Stubs  83155          92             84
6       Pace      Heading       Pace Heading  65015          85             91
1       Toby      Frankis       Toby Frankis  44094          80             97

In [18]:
# Find students with same Math and English score
df[df["math_score"] == df["english_score"]]

Empty DataFrame
Columns: [first_name, last_name, full name, id, math_score, english_score]
Index: []

In [19]:
# Use .query() to find students scoring over 95 in either subject
df.query("math_score > 95 or english_score > 95")

  first_name    last_name          full name     id  math_score  english_score
1       Toby      Frankis       Toby Frankis  44094          80             97
3    Deloris       Maffeo     Deloris Maffeo   6077          99             91
9      Grata  Hrishchenko  Grata Hrishchenko  12133         100             93

### 🧠 Mini-Challenge

> Load `"data/survey.csv"` and:
- Sort by the most recent signup date
- Filter out anyone who didn't complete the survey (nulls or "N/A")
- Use `.query()` to select rows with a specific condition of your choice

In [20]:
# The "survey.csv" couldn't be found
# I am using "mock_survey.csv" file that I generated using Mockaroo
# to complete this mini-challenge
from google.colab import files
uploaded = files.upload()

Saving mock_survey.csv to mock_survey.csv

In [21]:
df1 = pd.read_csv("mock_survey.csv")
df1.head()

,first_name,last_name,email,signup_date,completed_survey
0,Rog,Bines,rbines0@examiner.com,2/22/2024,yes
1,Xylina,Kennefick,xkennefick1@jugem.jp,4/28/2024,no
2,Winnah,Hartrick,whartrick2@networkadvertising.org,9/11/2024,no
3,Herb,Cansdale,hcansdale3@amazon.de,2/6/2024,yes
4,Nathalia,Bier,nbier4@tiny.cc,3/12/2024,no

In [29]:
# Before sorting, convert the signup date column into a real datetime format
df1["signup_date"] = pd.to_datetime(df1["signup_date"], errors="coerce")

# Sort by the most recent signup date
df1.sort_values(by="signup_date", ascending=False)

,first_name,last_name,email,signup_date,completed_survey
12,Lucila,Quinevan,lquinevanc@google.co.uk,2024-12-30,yes
2,Winnah,Hartrick,whartrick2@networkadvertising.org,2024-09-11,no
11,Stavros,Gero,sgerob@hp.com,2024-09-06,NaN
13,Berny,Pittam,bpittamd@mozilla.com,2024-08-30,NaN
6,Wynn,Howlett,whowlett6@dropbox.com,2024-07-17,yes
10,Ramona,Spracklin,rspracklina@sakura.ne.jp,2024-07-04,no
14,Guillemette,Jaimez,gjaimeze@chron.com,2024-05-06,NaN
1,Xylina,Kennefick,xkennefick1@jugem.jp,2024-04-28,no
9,Orville,Betke,obetke9@t.co,2024-04-13,NaN
5,Crystal,Hestrop,chestrop5@hhs.gov,2024-03-23,no
4,Nathalia,Bier,nbier4@tiny.cc,2024-03-12,no
7,Linet,Butner,lbutner7@hexun.com,2024-02-28,NaN
0,Rog,Bines,rbines0@examiner.com,2024-02-22,yes
3,Herb,Cansdale,hcansdale3@amazon.de,2024-02-06,yes
8,Brok,Tuft,btuft8@themeforest.net,2024-01-26,NaN

In [37]:
# Filter out anyone who didn't complete the survey
df1.dropna()

,first_name,last_name,email,signup_date,completed_survey
0,Rog,Bines,rbines0@examiner.com,2024-02-22,yes
1,Xylina,Kennefick,xkennefick1@jugem.jp,2024-04-28,no
2,Winnah,Hartrick,whartrick2@networkadvertising.org,2024-09-11,no
3,Herb,Cansdale,hcansdale3@amazon.de,2024-02-06,yes
4,Nathalia,Bier,nbier4@tiny.cc,2024-03-12,no
5,Crystal,Hestrop,chestrop5@hhs.gov,2024-03-23,no
6,Wynn,Howlett,whowlett6@dropbox.com,2024-07-17,yes
10,Ramona,Spracklin,rspracklina@sakura.ne.jp,2024-07-04,no
12,Lucila,Quinevan,lquinevanc@google.co.uk,2024-12-30,yes

In [41]:
# Use .query() to select rows where the survey was completed
df1.query("completed_survey == 'yes'")

   first_name last_name                    email signup_date completed_survey
0         Rog     Bines     rbines0@examiner.com  2024-02-22              yes
3        Herb  Cansdale     hcansdale3@amazon.de  2024-02-06              yes
6        Wynn   Howlett    whowlett6@dropbox.com  2024-07-17              yes
12     Lucila  Quinevan  lquinevanc@google.co.uk  2024-12-30              yes

### 📝 Summary

| Task              | Code Example                                 |
|-------------------|-----------------------------------------------|
| Sort by column     | `df.sort_values(by="col")`                  |
| Filter condition   | `df[df["col"] > value]`                     |
| Combine filters    | `df[(cond1) & (cond2)]`                     |
| Query method       | `df.query("col > value and col2 < value")`  |