<a href="https://colab.research.google.com/github/thaiyenphung/thaiyenphung-DataScience-2025/blob/main/Completed/05-Foundations/04-data_input_output.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📊 04 - Data Input and Output

Most of data science is about **loading data, exploring it, and saving results**.  
In this notebook you will learn:
- Reading CSV files with Pandas
- Inspecting DataFrames (`head`, `info`, `describe`)
- Writing data back to CSV
- Reading Excel files (if available)

## 1. Reading CSV Files

In [1]:
import pandas as pd

# Create a small CSV for demo
data = """Name,Age,Score
Alice,23,90
Bob,25,85
Charlie,22,95
"""
with open("students.csv", "w") as f:
    f.write(data)

# Read CSV into DataFrame
df = pd.read_csv("students.csv")
df

      Name  Age  Score
0    Alice   23     90
1      Bob   25     85
2  Charlie   22     95

✅ **Your Turn**: Create your own small CSV (3–5 rows) and read it into Pandas.

In [15]:
import pandas as pd

# Create a CSV file
data = """Movie,Genre,Release Year
          Inception,Science Fiction,2010
          Forrest Gump,Drama,1994
          Top Gun: Maverick,Action,2022
          """
with open("movies.csv", "w") as f:
    f.write(data)

# Read CSV into DataFrame
df = pd.read_csv("movies.csv")

# Print the content in DataFrame
df

                         Movie            Genre  Release Year
0                    Inception  Science Fiction          2010
1                 Forrest Gump            Drama          1994
2            Top Gun: Maverick           Action          2022

## 2. Exploring DataFrames

In [16]:
# Look at the first rows
df.head()

                         Movie            Genre  Release Year
0                    Inception  Science Fiction          2010
1                 Forrest Gump            Drama          1994
2            Top Gun: Maverick           Action          2022

In [17]:
# Info about columns and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Movie         3 non-null      object
 1   Genre         3 non-null      object
 2   Release Year  3 non-null      int64
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [18]:
# Summary statistics
df.describe()

       Release Year
count      3.000000
mean    2008.666667
std       14.047538
min     1994.000000
25%     2002.000000
50%     2010.000000
75%     2016.000000
max     2022.000000

✅ **Your Turn**: Use `.head()` to preview your dataset and `.describe()` to see basic statistics.

In [19]:
df.head()

                         Movie            Genre  Release Year
0                    Inception  Science Fiction          2010
1                 Forrest Gump            Drama          1994
2            Top Gun: Maverick           Action          2022

In [20]:
df.describe()

       Release Year
count      3.000000
mean    2008.666667
std       14.047538
min     1994.000000
25%     2002.000000
50%     2010.000000
75%     2016.000000
max     2022.000000

## 3. Writing CSV Files

In [21]:
# Save the DataFrame to a new CSV
df.to_csv("students_copy.csv", index=False)
%ls *.csv

movies.csv  students_copy.csv  students.csv

✅ **Your Turn**: Save your DataFrame to a CSV file called `my_data.csv`.

In [22]:
df.to_csv("my_data.csv", index = False)
%ls *.csv

movies.csv  my_data.csv  students_copy.csv  students.csv

## 4. Reading Excel Files

In [24]:
# Optional: Requires 'openpyxl' installed
# Save to Excel
df.to_excel("students.xlsx", index=False)

# Read Excel file
pd.read_excel("students.xlsx")

                         Movie            Genre  Release Year
0                    Inception  Science Fiction          2010
1                 Forrest Gump            Drama          1994
2            Top Gun: Maverick           Action          2022

✅ **Your Turn**: Try saving your dataset to Excel and reading it back (if supported in your environment).

In [25]:
# Save dataset to Excel
df.to_excel("movies.xlsx", index = False)

# Read the Excel file
pd.read_excel("movies.xlsx")

                         Movie            Genre  Release Year
0                    Inception  Science Fiction          2010
1                 Forrest Gump            Drama          1994
2            Top Gun: Maverick           Action          2022

---
### Summary
- `pd.read_csv` loads data into a DataFrame.
- Use `.head()`, `.info()`, `.describe()` to explore quickly.
- `df.to_csv` and `df.to_excel` save results.
- Pandas makes file I/O simple and reliable.